### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by zopieux** [prologin/django-massmailer#2]
- [x] `query_parser`
- [ ] adding, editing a template
- [ ] adding, editing a query
- [x] template rendering
- [ ] query execution
- [ ] sending a batch
- [ ] actual batch mail sending with Celery & SMTP
- [ ] batch mail retry with Celery & SMTP

**Comment by kolowy** [comment]
Migrated to https://gitlab.com/prologin/tech/packages/django-massmailer/-/issues/2
